### ISSUE TITLE
Precision checks in external function calls

### ISSUE THREAD

**Issue by huangyihe** [huangyihe/llvm-3.6.0#24]
Since we cannot do anything about uninterpreted external function calls (because the interpreter can't interpret x86 assembly), we need a reasonable way to incorporate them into our system.

We can always assume that they don't lose precision, so we only check the arguments provided to these functions.

@danking commented in #16 that "We could also compute an error of the output based on a function of the input errors", which is also a good way of reducing the amount of garbage we generate on screen right now. But for functions like `printf` I really don't know what would the correct model be. Perhaps we need to talk to Eddie about this.

**Comment by danking** [comment]
`printf` shouldn't be an issue because it doesn't return anything. The problematic cases are things that return `float`s or `double`s.

I think we should punt for now, but if we come across widely used numeric libraries, we could just package them ourselves for use with the tool.

We should probably ask @kohler for guidance.
